title = "Adam Binks"
baseURL = "https://adambinks.me"
theme = ["hugo-redirect", "researcher"]
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
# googleAnalytics = "G-K15E0YCM0F"  # add your tracking id

[params]
  author = "Adam Binks"
  description = "PhD student at the University of St Andrews."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  [params.footer]
    text = ":)"
    url = "#"

[permalinks]
  "/" = "/:filename"

[menu]
    [[menu.main]]
        name = "LinkedIn"
        url = "https://linkedin.com/in/adam-binks/"
    [[menu.main]]
        name = "Twitter"
        url = "https://twitter.com/adambinks_"
    [[menu.main]]
        name = "Write Reason"
        url = "https://adambinks.me/write-reason/"
    [[menu.main]]
        name = "Map of Why"
        url = "https://adambinks.me/map-of-why/"

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
